"""Agent G - Amazon Fashion Shorts Generator.
ASIN-based affiliate links + Gemini short-form scripts + image generation.
"""
import os
import re
import json
import random
from datetime import datetime, timezone
from urllib.parse import quote_plus
from google import genai
from config import GEMINI_API_KEY, AMAZON_TAG
from safety import tracker

OUTPUT_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'data', 'shorts')

# Amazon fashion trending items (rotate daily)
TRENDING_ITEMS = [
    {"name": "Lightweight Fleece", "asin": "B0CMV1K7NR"},
    {"name": "Wide Leg Denim", "asin": "B0CH1M6X9Q"},
    {"name": "Teal Knit Sweater", "asin": "B0CNX8X6Y5"},
    {"name": "Satin Slip Dress", "asin": "B0BXKL8MQV"},
    {"name": "Oversized Blazer Women", "asin": "B0C1JQ8GKT"},
    {"name": "Platform Sneakers Women", "asin": "B0BZ3WMFYQ"},
    {"name": "Cashmere Crewneck Sweater", "asin": "B0BVLCWKP6"},
    {"name": "High Waist Wide Leg Pants", "asin": "B0C7TDJM4H"},
    {"name": "Leather Crossbody Bag", "asin": "B0CDKJL8WR"},
    {"name": "Minimal Gold Hoop Earrings", "asin": "B0B5BKZQVT"},
]


def _make_asin_link(asin):
    return f"https://www.amazon.com/dp/{asin}/?tag={AMAZON_TAG}"


def _make_search_link(keyword):
    encoded = quote_plus(keyword)
    return f"https://www.amazon.com/s?k={encoded}&tag={AMAZON_TAG}"


def generate_shorts_content():
    """Generate short-form scripts + image prompts for 3 daily picks."""
    if not GEMINI_API_KEY:
        print('[AmazonShorts] No GEMINI_API_KEY. Skipping.')
        return []

    client = genai.Client(api_key=GEMINI_API_KEY)
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    today = datetime.now(timezone.utc).strftime('%Y-%m-%d')
    results = []

    # Pick 3 items for today
    daily_picks = random.sample(TRENDING_ITEMS, min(3, len(TRENDING_ITEMS)))

    for i, item in enumerate(daily_picks, 1):
        asin_link = _make_asin_link(item['asin'])
        search_link = _make_search_link(item['name'])

        prompt = f"""You are TrendLoop USA's fashion content creator for short-form video (TikTok, Reels, Shorts).

Product: {item['name']}
ASIN: {item['asin']}
Affiliate Link: {asin_link}
Search Link: {search_link}

Create a complete short-form video content package:

1. HOOK (first 3 seconds, punchy, attention-grabbing):
   One powerful opening line.

2. SCRIPT (30-60 seconds, conversational, Gen Z friendly tone):
   - Why this item is trending in 2026
   - How to style it (3 outfit ideas)
   - Call to action with link reference

3. IMAGE_PROMPT_1: Photorealistic editorial fashion photo prompt featuring this item, studio lighting, clean background
4. IMAGE_PROMPT_2: Street style photo prompt with this item, urban setting, golden hour
5. IMAGE_PROMPT_3: Flat lay product photo prompt, minimalist aesthetic, marble background

6. CAPTION: Social media caption with hashtags (max 200 chars)
7. PIN_DESCRIPTION: Pinterest description with hashtags (max 300 chars)

IMPORTANT: Include 'Generated by AI' disclosure note.
Output format - use these exact labels:
HOOK: ...
SCRIPT: ...
IMAGE_PROMPT_1: ...
IMAGE_PROMPT_2: ...
IMAGE_PROMPT_3: ...
CAPTION: ...
PIN_DESCRIPTION: ...
DISCLOSURE: Generated by AI | TrendLoop USA"""

        try:
            response = client.models.generate_content(
                model='gemini-2.5-flash',
                contents=prompt,
            )
            tracker.log_api_call('gemini')
            content = response.text

            result = {
                'date': today,
                'item_name': item['name'],
                'asin': item['asin'],
                'asin_link': asin_link,
                'search_link': search_link,
                'content': content,
                'index': i,
            }
            results.append(result)
            print(f'[AmazonShorts] {i}/3 Generated: {item["name"]}')

        except Exception as e:
            print(f'[AmazonShorts] Error for {item["name"]}: {e}')
            tracker.log_error('gemini')

    # Save results
    output_file = os.path.join(OUTPUT_DIR, f'{today}-shorts.json')
    with open(output_file, 'w', encoding='utf-8') as f:
        json.dump(results, f, ensure_ascii=False, indent=2)

    print(f'[AmazonShorts] Saved {len(results)} scripts to {output_file}')

    # Generate images for each script
    _generate_images(client, results, today)

    return results


def _generate_images(client, results, date):
    """Generate images using Gemini for each shorts script."""
    img_dir = os.path.join(OUTPUT_DIR, date)
    os.makedirs(img_dir, exist_ok=True)

    for r in results:
        content = r.get('content', '')
        # Extract first image prompt
        match = re.search(r'IMAGE_PROMPT_1:\s*(.+)', content)
        if not match:
            continue

        img_prompt = match.group(1).strip()
        try:
            response = client.models.generate_content(
                model='gemini-2.0-flash-exp-image-generation',
                contents=img_prompt,
            )
            tracker.log_api_call('gemini')

            # Save image if returned
            if response.candidates and response.candidates[0].content.parts:
                for part in response.candidates[0].content.parts:
                    if hasattr(part, 'inline_data') and part.inline_data:
                        img_data = part.inline_data.data
                        safe_name = re.sub(r'[^a-z0-9]', '-', r['item_name'].lower())[:30]
                        img_path = os.path.join(img_dir, f'{safe_name}.png')
                        with open(img_path, 'wb') as f:
                            f.write(img_data)
                        print(f'[AmazonShorts] Image saved: {img_path}')
                        break
        except Exception as e:
            print(f'[AmazonShorts] Image gen error: {e}')
            tracker.log_error('gemini')


if __name__ == '__main__':
    print('=== Amazon Shorts Generator ===')
    generate_shorts_content()
